### ISSUE TITLE
Initial render produces 404 (Not Found) error

### ISSUE THREAD

**Issue by dixonsiu** [personium/app-myboard#10]
The following is display in the debug console. Why is it trying to access unrelated cells? Should I ignore these errors?

    GET https://demo.personium.io/hn-user-9001/io_personium_demo_app-myboard/MyBoardBox/my-board.json 404 (Not Found)
    {"code":"PR404-DV-0002","message":{"lang":"en","value":"Box not found at [https://demo.personium.io/hn-user-9001/io_personium_demo_app-myboard]."}}
    
    GET https://demo.personium.io/hn-user-9011/io_personium_demo_app-myboard/MyBoardBox/my-board.json 404 (Not Found)
    {"code":"PR404-DV-0002","message":{"lang":"en","value":"Box not found at [https://demo.personium.io/hn-user-9011/io_personium_demo_app-myboard]."}}

**Comment by csKyou** [comment]
In order to check the cell in which myBoard is installed, we are trying to obtain the json file for all the external cells. It is an error that can be ignored.

**Comment by dixonsiu** [comment]
Since we only need to handle 403 error, added the following to mb.checkOtherAllowedCells.

        // Insufficient access privileges
        if (data.status === 403) {
            mb.appendRequestCells(extUrl, dispName);
        }
